// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectKrakenSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectKrakenSpotWebsocket'](arg1);
}

export function FetchKrakenSpotPairs() {
  return window['go']['main']['App']['FetchKrakenSpotPairs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
