// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectBinanceCoinmWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBinanceCoinmWebsocket'](arg1);
}

export function ConnectBinanceSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBinanceSpotWebsocket'](arg1);
}

export function ConnectBinanceUsWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBinanceUsWebsocket'](arg1);
}

export function ConnectBinanceUsdmWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBinanceUsdmWebsocket'](arg1);
}

export function ConnectBitgetFuturesWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBitgetFuturesWebsocket'](arg1);
}

export function ConnectBitgetSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBitgetSpotWebsocket'](arg1);
}

export function ConnectBybitFuturesWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBybitFuturesWebsocket'](arg1);
}

export function ConnectBybitSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBybitSpotWebsocket'](arg1);
}

export function ConnectKrakenSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectKrakenSpotWebsocket'](arg1);
}

export function FetchBinanceCoinmPairs() {
  return window['go']['main']['App']['FetchBinanceCoinmPairs']();
}

export function FetchBinanceSpotPairs() {
  return window['go']['main']['App']['FetchBinanceSpotPairs']();
}

export function FetchBinanceUsSpotPairs() {
  return window['go']['main']['App']['FetchBinanceUsSpotPairs']();
}

export function FetchBinanceUsdmPairs() {
  return window['go']['main']['App']['FetchBinanceUsdmPairs']();
}

export function FetchBitgetFuturesPairs() {
  return window['go']['main']['App']['FetchBitgetFuturesPairs']();
}

export function FetchBitgetSpotPairs() {
  return window['go']['main']['App']['FetchBitgetSpotPairs']();
}

export function FetchBybitFuturesPairs() {
  return window['go']['main']['App']['FetchBybitFuturesPairs']();
}

export function FetchBybitSpotPairs() {
  return window['go']['main']['App']['FetchBybitSpotPairs']();
}

export function FetchCoinbaseSpotPairs() {
  return window['go']['main']['App']['FetchCoinbaseSpotPairs']();
}

export function FetchKrakenFuturesPairs() {
  return window['go']['main']['App']['FetchKrakenFuturesPairs']();
}

export function FetchKrakenSpotPairs() {
  return window['go']['main']['App']['FetchKrakenSpotPairs']();
}

export function FetchOkxSpotPairs() {
  return window['go']['main']['App']['FetchOkxSpotPairs']();
}

export function FetchOkxSwapsPairs() {
  return window['go']['main']['App']['FetchOkxSwapsPairs']();
}

export function FetchUpbitSpotPairs() {
  return window['go']['main']['App']['FetchUpbitSpotPairs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
