// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectKrakenSpotWebsocket(arg1:string):Promise<void>;

export function FetchBinanceSpotPairs():Promise<Array<string>>;

export function FetchKrakenSpotPairs():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;
