// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectBinanceCoinmWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBinanceCoinmWebsocket'](arg1);
}

export function ConnectBinanceSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBinanceSpotWebsocket'](arg1);
}

export function ConnectBinanceUsWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBinanceUsWebsocket'](arg1);
}

export function ConnectBinanceUsdmWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBinanceUsdmWebsocket'](arg1);
}

export function ConnectBitgetFuturesWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBitgetFuturesWebsocket'](arg1);
}

export function ConnectBitgetSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBitgetSpotWebsocket'](arg1);
}

export function ConnectBybitFuturesWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBybitFuturesWebsocket'](arg1);
}

export function ConnectBybitSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectBybitSpotWebsocket'](arg1);
}

export function ConnectCoinbaseSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectCoinbaseSpotWebsocket'](arg1);
}

export function ConnectDydxWebsocket(arg1) {
  return window['go']['main']['App']['ConnectDydxWebsocket'](arg1);
}

export function ConnectHyperliquidxWebsocket(arg1) {
  return window['go']['main']['App']['ConnectHyperliquidxWebsocket'](arg1);
}

export function ConnectKrakenFuturesWebsocket(arg1) {
  return window['go']['main']['App']['ConnectKrakenFuturesWebsocket'](arg1);
}

export function ConnectKrakenSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectKrakenSpotWebsocket'](arg1);
}

export function ConnectOkxSpotWebsocket(arg1) {
  return window['go']['main']['App']['ConnectOkxSpotWebsocket'](arg1);
}

export function ConnectOkxSwapsWebsocket(arg1) {
  return window['go']['main']['App']['ConnectOkxSwapsWebsocket'](arg1);
}

export function ConnectUpbitWebsocket(arg1) {
  return window['go']['main']['App']['ConnectUpbitWebsocket'](arg1);
}

export function FetchPairs(arg1) {
  return window['go']['main']['App']['FetchPairs'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
