// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectBinanceCoinmWebsocket(arg1:string):Promise<void>;

export function ConnectBinanceSpotWebsocket(arg1:string):Promise<void>;

export function ConnectBinanceUsWebsocket(arg1:string):Promise<void>;

export function ConnectBinanceUsdmWebsocket(arg1:string):Promise<void>;

export function ConnectBitgetFuturesWebsocket(arg1:string):Promise<void>;

export function ConnectBitgetSpotWebsocket(arg1:string):Promise<void>;

export function ConnectBybitFuturesWebsocket(arg1:string):Promise<void>;

export function ConnectBybitSpotWebsocket(arg1:string):Promise<void>;

export function ConnectCoinbaseSpotWebsocket(arg1:string):Promise<void>;

export function ConnectKrakenSpotWebsocket(arg1:string):Promise<void>;

export function FetchBinanceCoinmPairs():Promise<Array<string>>;

export function FetchBinanceSpotPairs():Promise<Array<string>>;

export function FetchBinanceUsSpotPairs():Promise<Array<string>>;

export function FetchBinanceUsdmPairs():Promise<Array<string>>;

export function FetchBitgetFuturesPairs():Promise<Array<string>>;

export function FetchBitgetSpotPairs():Promise<Array<string>>;

export function FetchBybitFuturesPairs():Promise<Array<string>>;

export function FetchBybitSpotPairs():Promise<Array<string>>;

export function FetchCoinbaseSpotPairs():Promise<Array<string>>;

export function FetchKrakenFuturesPairs():Promise<Array<string>>;

export function FetchKrakenSpotPairs():Promise<Array<string>>;

export function FetchOkxSpotPairs():Promise<Array<string>>;

export function FetchOkxSwapsPairs():Promise<Array<string>>;

export function FetchUpbitSpotPairs():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;
