// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWebsocket(arg1:string,arg2:string):Promise<void>;

export function FetchPairs(arg1:string):Promise<Array<string>>;
